image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: registry.gitlab.com/$CI_PROJECT_PATH:latest

before_script:
  - apk add --no-cache openjdk17 maven
  - java -version
  - mvn -version
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-and-push:
  stage: deploy
  script:
    - mvn clean package -DskipTests
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - main
